{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.10","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# This Python 3 environment comes with many helpful analytics libraries installed\n# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n# For example, here's several helpful packages to load\n\nimport numpy as np # linear algebra\nimport pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n\n# Input data files are available in the read-only \"../input/\" directory\n# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n\nimport os\nfor dirname, _, filenames in os.walk('/kaggle/input'):\n    for filename in filenames:\n        print(os.path.join(dirname, filename))\n\n# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"","metadata":{"execution":{"iopub.status.busy":"2023-06-30T21:18:10.682073Z","iopub.execute_input":"2023-06-30T21:18:10.682488Z","iopub.status.idle":"2023-06-30T21:18:12.084807Z","shell.execute_reply.started":"2023-06-30T21:18:10.682448Z","shell.execute_reply":"2023-06-30T21:18:12.083121Z"},"trusted":true},"execution_count":1,"outputs":[{"name":"stdout","text":"Traceback (most recent call last):\n  File \"/opt/conda/bin/kaggle\", line 5, in <module>\n    from kaggle.cli import main\n  File \"/opt/conda/lib/python3.10/site-packages/kaggle/__init__.py\", line 23, in <module>\n    api.authenticate()\n  File \"/opt/conda/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py\", line 164, in authenticate\n    raise IOError('Could not find {}. Make sure it\\'s located in'\nOSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.\n","output_type":"stream"}]},{"cell_type":"code","source":"!ls -al /kaggle/input/kagglejson","metadata":{"execution":{"iopub.status.busy":"2023-06-30T21:23:44.342393Z","iopub.execute_input":"2023-06-30T21:23:44.343621Z","iopub.status.idle":"2023-06-30T21:23:45.439633Z","shell.execute_reply.started":"2023-06-30T21:23:44.343579Z","shell.execute_reply":"2023-06-30T21:23:45.438280Z"},"trusted":true},"execution_count":6,"outputs":[{"name":"stdout","text":"total 8\ndrwxr-xr-x 2 nobody nogroup    0 Jun 30 21:22 .\ndrwxr-xr-x 3 root   root    4096 Jun 30 21:22 ..\n-rw-r--r-- 1 nobody nogroup   64 Jun 30 21:22 kaggle.json\n","output_type":"stream"}]},{"cell_type":"code","source":"#!mkdir ~/.kaggle\n#! cp /kaggle/input/kagglejson/kaggle.json ~/.kaggle/\n#! chmod 600 ~/.kaggle/kaggle.json\n! ls -al ~/.kaggle","metadata":{"execution":{"iopub.status.busy":"2023-06-30T21:26:13.762033Z","iopub.execute_input":"2023-06-30T21:26:13.762973Z","iopub.status.idle":"2023-06-30T21:26:14.872798Z","shell.execute_reply.started":"2023-06-30T21:26:13.762932Z","shell.execute_reply":"2023-06-30T21:26:14.870907Z"},"trusted":true},"execution_count":11,"outputs":[{"name":"stdout","text":"total 16\ndrwxr-xr-x 2 root root 4096 Jun 30 21:25 .\ndrwx------ 1 root root 4096 Jun 30 21:18 ..\n-rw------- 1 root root   64 Jun 30 21:25 kaggle.json\n","output_type":"stream"}]},{"cell_type":"code","source":"!kaggle datasets download ardamavi/sign_language_digits","metadata":{"execution":{"iopub.status.busy":"2023-06-30T21:26:59.439351Z","iopub.execute_input":"2023-06-30T21:26:59.439764Z","iopub.status.idle":"2023-06-30T21:27:01.035775Z","shell.execute_reply.started":"2023-06-30T21:26:59.439729Z","shell.execute_reply":"2023-06-30T21:27:01.034687Z"},"trusted":true},"execution_count":12,"outputs":[{"name":"stdout","text":"403 - Forbidden\n","output_type":"stream"}]},{"cell_type":"code","source":"!ls -al /kaggle/input/ardamavi-sign-language-digits","metadata":{"execution":{"iopub.status.busy":"2023-06-30T21:40:35.114392Z","iopub.execute_input":"2023-06-30T21:40:35.114833Z","iopub.status.idle":"2023-06-30T21:40:36.194780Z","shell.execute_reply.started":"2023-06-30T21:40:35.114798Z","shell.execute_reply":"2023-06-30T21:40:36.193489Z"},"trusted":true},"execution_count":16,"outputs":[{"name":"stdout","text":"total 4\ndrwxr-xr-x 3 nobody nogroup    0 Jun 30 21:32 .\ndrwxr-xr-x 3 root   root    4096 Jun 30 21:32 ..\ndrwxr-xr-x 2 nobody nogroup    0 Jun 30 21:32 Sign-language-digits-dataset\n","output_type":"stream"}]},{"cell_type":"code","source":"#kaggle api token\nimport tensorflow as tf\n\n# Import the American Sign Language digits database\nimport kaggle.datasets as datasets\n\n# Specify the directory where the dataset will be downloaded\n#dataset_dir = '/path/to/sign_language_digits/'\n#dataset_dir = './data/sign_language_digits/'\n\n# Download the dataset\n#datasets.load_dataset('ardamavi/sign_language_digits', data_dir=dataset_dir, api_key='<your_api_token>')\n#datasets.load_dataset('ardamavi/sign_language_digits', data_dir=dataset_dir, api_key='ebdee7b9eb97fe61d9250572fe9b2730')\n\n# Load the training and test sets\n#(train_images, train_labels), (test_images, test_labels) = datasets.load_dataset('ardamavi/sign_language_digits', split='train', download=True, api_key='ebdee7b9eb97fe61d9250572fe9b2730')\n(train_images, train_labels), (test_images, test_labels) = \\\n    datasets.load_dataset(\"/kaggle/input/ardamavi-sign-language-digits/Sign-language-digits-dataset\", split='train', download=True, api_key='ebdee7b9eb97fe61d9250572fe9b2730')\n\n# Scale the images to a range of 0 to 1\ntrain_images = train_images / 255.0\ntest_images = test_images / 255.0\n\n# Create the model\nmodel = tf.keras.models.Sequential([\n  tf.keras.layers.Flatten(input_shape=(28, 28)),\n  tf.keras.layers.Dense(128, activation='relu'),\n  tf.keras.layers.Dense(10, activation='softmax')\n])\n\n# Compile the model\nmodel.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])\n\n# Train the model\nmodel.fit(train_images, train_labels, epochs=10)\n\n# Evaluate the model\nmodel.evaluate(test_images, test_labels)\n\n# Save the model\nmodel.save('hand_sign_classification_model.h5')","metadata":{"execution":{"iopub.status.busy":"2023-06-30T21:41:52.367021Z","iopub.execute_input":"2023-06-30T21:41:52.367463Z","iopub.status.idle":"2023-06-30T21:42:01.465445Z","shell.execute_reply.started":"2023-06-30T21:41:52.367432Z","shell.execute_reply":"2023-06-30T21:42:01.463940Z"},"trusted":true},"execution_count":18,"outputs":[{"name":"stderr","text":"/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']\ncaused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']\n  warnings.warn(f\"unable to load libtensorflow_io_plugins.so: {e}\")\n/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']\ncaused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']\n  warnings.warn(f\"file system plugins are not loaded: {e}\")\n","output_type":"stream"},{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)","Cell \u001b[0;32mIn[18], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtensorflow\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mtf\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;66;03m# Import the American Sign Language digits database\u001b[39;00m\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mkaggle\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdatasets\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mdatasets\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;66;03m# Specify the directory where the dataset will be downloaded\u001b[39;00m\n\u001b[1;32m      8\u001b[0m \u001b[38;5;66;03m#dataset_dir = '/path/to/sign_language_digits/'\u001b[39;00m\n\u001b[1;32m      9\u001b[0m \u001b[38;5;66;03m#dataset_dir = './data/sign_language_digits/'\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[38;5;66;03m# Load the training and test sets\u001b[39;00m\n\u001b[1;32m     16\u001b[0m \u001b[38;5;66;03m#(train_images, train_labels), (test_images, test_labels) = datasets.load_dataset('ardamavi/sign_language_digits', split='train', download=True, api_key='ebdee7b9eb97fe61d9250572fe9b2730')\u001b[39;00m\n\u001b[1;32m     17\u001b[0m (train_images, train_labels), (test_images, test_labels) \u001b[38;5;241m=\u001b[39m \\\n\u001b[1;32m     18\u001b[0m     datasets\u001b[38;5;241m.\u001b[39mload_dataset(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m/kaggle/input/ardamavi-sign-language-digits/Sign-language-digits-dataset\u001b[39m\u001b[38;5;124m\"\u001b[39m, split\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtrain\u001b[39m\u001b[38;5;124m'\u001b[39m, download\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m, api_key\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mebdee7b9eb97fe61d9250572fe9b2730\u001b[39m\u001b[38;5;124m'\u001b[39m)\n","\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'kaggle.datasets'"],"ename":"ModuleNotFoundError","evalue":"No module named 'kaggle.datasets'","output_type":"error"}]}]}